apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1y4e
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1y4e
    app.kubernetes.io/part-of: tkrw-pr714-0075-0031-app
  name: devfile-sample-1y4e
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-1y4e
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-1y4e
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0031-tenant/tkrw-pr714-0075-0031-app/devfile-sample-1y4e@sha256:9bedacfef81283d311a0cd06287f0105e537fc0b6e0c1e6ba1d7dde4e9dec8e4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
